### ISSUE TITLE
Simplify debug representation of partial type

### ISSUE THREAD

**Issue by t-moe** [bengreenier/partially#11]
I have another feature request :)

Currently when i `#[partially(derive(Debug))]` and then print a partial, the output contains a lot of None's.
I would be nice if there was some way of only printing the options that contain values.

E.g. we could create a trait PartialDebug which mirrors core::fmt::Debug, but skips Options containing None. And then we crate a blanked implementation for Debug if T : PartialDebug. As a result I could  `#[partially(derive(ParitialDebug))]` to get a more compact debug representation of my partial.

EDIT: or even better, create a trait PartialDebug which inherits core::fmt::Debug and when deriving that, leave out the None's. Not sure this is possible though....

**Comment by bengreenier** [comment]
I don't think this one belongs in this crate - a separate crate should provide such an implementation. For instance, [educe](https://crates.io/crates/educe) provides a way to implement debug using another method or trait, which is _almost_ enough for this (though presumably you want to autogenerate the impl).

I agree there's scenarios where it's nice to be able to print a version of the struct without the `None`s, but since `partially` doesn't enforce the `derive(Debug)` in the first place, I think it'd be unusual to provide a `Debug` implementation here, and doubly so for one with an opinionated approach like skipping `None`.

That said, I'd be open to having some `partially_utils` or similarly named crate that contains things like this - but currently this is the only idea for that, so I'm not ready to develop it (would happily support you doing that work though, if you're interested).

**Comment by bengreenier** [comment]
I'll close this for now, but feel free to continue the conversation here - and if you're interested in that work, let me know and we can reopen/create some better tracking issue.

**Comment by t-moe** [comment]
@bengreenier 
(I wanted to say thank you for #7 and #8 a while ago, but then I forgot :).  )
Thank you so much, for implementing this on such short notice. You're doing an awesome job!

Regarding the ticket here: I understand your reasoning and I can live with it :+1:
